# Generated by Django 4.2.7 on 2026-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('idea', 'Только идея'), ('prototype', 'Прототип'), ('demo', 'Демо-версия'), ('alpha', 'Альфа-тест'), ('beta', 'Бета-тест'), ('released', 'Релиз')], default='idea', max_length=20, verbose_name='Статус разработки'),
        ),
    ]
