# Generated by Django 4.2.7 on 2026-05-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='uploaded_at',
        ),
    ]
